.\" -*- mode: nroff; -*-
.\"
.\" SPDX-FileCopyrightText: Copyright 2024 Markus Uhlin
.\" SPDX-License-Identifier: ISC
.\"
.Dd March 12, 2024
.Dt FICS_ADDPLAYER 1
.Os
.Sh NAME
.Nm fics_addplayer
.Nd creates a registered chess player
.Sh SYNOPSIS
.Nm fics_addplayer
.Aq UserName
.Aq FullName
.Aq EmailAddress
.Sh DESCRIPTION
.Nm
creates a registered chess player on a server that runs FICS.
An email will be sent to the given address with the login details.
.Sh SEE ALSO
.Xr fics 1 , Xr makerank 1
