.\" -*- mode: nroff; -*-
.\"
.\" SPDX-FileCopyrightText: Copyright 2024 Markus Uhlin
.\" SPDX-License-Identifier: ISC
.\"
.Dd March 12, 2024
.Dt FICS 1
.Os
.Sh NAME
.Nm fics
.Nd free internet chess server fork
.Sh SYNOPSIS
.Nm fics
.Bk -words
.Op Fl h
.Op Fl p Ar port
.Ek
.Sh DESCRIPTION
.Nm
is a free internet chess server originally developed by Richard Nash
in the mid 90's.
This manual page however documents a fork of
.Nm
developed by the
.Lk www.rpblc.net RPBLC
computing network.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h
Outputs the program usage.
.It Fl p Ar port
Which port shall the chess server listen on?
(The default is 5000.)
.El
.Sh FICS CLIENT
While it's possible to play chess via the terminal by connecting to a
server using
.Xr telnet 1 ,
it can be a lot easier to play with a GUI client like
.Xr xboard 1 .
To connect to a server by using
.Xr xboard 1 ,
try:
.Bd -literal -offset indent
xboard -ics -icshost server.hostname.com
.Ed
.Sh SEE ALSO
.Xr fics_addplayer 1 , Xr makerank 1
.Sh AUTHORS
This manual page was written by
.An Markus Uhlin
.Aq Mt maxxe@rpblc.net
