.\" -*- mode: nroff; -*-
.Dd March 15, 2024
.Dt MAKERANK 1
.Os
.Sh NAME
.Nm makerank
.Nd creates rankings for FICS games
.Sh SYNOPSIS
Takes no arguments.
.Sh DESCRIPTION
.Nm
creates sorted rankings for FICS (Free Internet Chess Server) games
and writes them to the hard disk.
Currently for the following game types:
.Bl -bullet -compact
.It
std
.It
blitz
.It
wild
.It
lightning
.El
.Sh SEE ALSO
.Xr fics 1 , Xr fics_addplayer 1
