# Makefile for FICS
# This was originally written under NeXTSTEP
#
# Define the system below that you are compiling on.

SYSFLAG=-DSYSTEM_SUN4 

# Set the flags for your system

# Turn on optimization
# With optimization on you may get errors during compiling.
OPTFLAGS=

# Turn on debugging
#DEBUGFLAGS=-DDEBUG 

# Anything else you care to flag?
#OTHERFLAGS=-traditional-cpp -Wall -g
OTHERFLAGS=-Wall -g

# Which architectures are you compiling for? (NeXTSTEP)
# ARCHFLAGS=-arch m68k -arch i386

PROGRAM=fics


CC=gcc
#cc doesn't seem to be supported at present.

CFLAGS=${SYSFLAG} ${OPTFLAGS} ${DEBUGFLAGS} ${OTHERFLAGS} ${ARCHFLAGS}
LNFLAGS=-lm

# dfree is temporary, for debugging only, and works only if you are using
# the GNU C library --mann 
#MORESRCS=dfree.c
#MOREOBJS=dfree.o
#you may have to hash out the above two

# This is just for versions distributed with timeseal.
MORESRCS=timeseal.c
MOREOBJS=timeseal.o
SYSFLAG=-DSYSTEM_SUN4 -DTIMESEAL

# The following is needed when using gcc and glibc, as on caissa.
MAKEDEPMORECFLAGS= -I/usr/local/include -I/usr/local/lib/gcc-lib/sparc-sun-sunos4.1.3/2.6.3/include

include ./Makefile.common
# include ./Makedist

#run makedepend to fill out the info below
# DO NOT DELETE THIS LINE -- make depend depends on it.

adminproc.o: stdinclude.h /usr/local/include/sys/types.h
adminproc.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
adminproc.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
adminproc.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
adminproc.o: /usr/local/include/strings.h /usr/local/include/string.h
adminproc.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
adminproc.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
adminproc.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
adminproc.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
adminproc.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
adminproc.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
adminproc.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
adminproc.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
adminproc.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
adminproc.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
adminproc.o: /usr/local/include/signal.h /usr/local/include/sigset.h
adminproc.o: /usr/local/include/math.h /usr/local/include/huge_val.h
adminproc.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
adminproc.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
adminproc.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
adminproc.o: /usr/local/include/sys/ttydefaults.h
adminproc.o: /usr/local/include/sys/wait.h /usr/local/include/waitflags.h
adminproc.o: /usr/local/include/waitstatus.h common.h vers.h legal.h
adminproc.o: network.h command.h variable.h adminproc.h playerdb.h gamedb.h
adminproc.o: board.h gameproc.h ratings.h utils.h multicol.h rmalloc.h
adminproc.o: talkproc.h comproc.h
algcheck.o: stdinclude.h /usr/local/include/sys/types.h
algcheck.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
algcheck.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
algcheck.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
algcheck.o: /usr/local/include/strings.h /usr/local/include/string.h
algcheck.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
algcheck.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
algcheck.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
algcheck.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
algcheck.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
algcheck.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
algcheck.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
algcheck.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
algcheck.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
algcheck.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
algcheck.o: /usr/local/include/signal.h /usr/local/include/sigset.h
algcheck.o: /usr/local/include/math.h /usr/local/include/huge_val.h
algcheck.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
algcheck.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
algcheck.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
algcheck.o: /usr/local/include/sys/ttydefaults.h
algcheck.o: /usr/local/include/sys/wait.h /usr/local/include/waitflags.h
algcheck.o: /usr/local/include/waitstatus.h common.h vers.h legal.h
algcheck.o: algcheck.h board.h movecheck.h utils.h multicol.h
board.o: stdinclude.h /usr/local/include/sys/types.h
board.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
board.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
board.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
board.o: /usr/local/include/strings.h /usr/local/include/string.h
board.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
board.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
board.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
board.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
board.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
board.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
board.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
board.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
board.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
board.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
board.o: /usr/local/include/signal.h /usr/local/include/sigset.h
board.o: /usr/local/include/math.h /usr/local/include/huge_val.h
board.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
board.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
board.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
board.o: /usr/local/include/sys/ttydefaults.h /usr/local/include/sys/wait.h
board.o: /usr/local/include/waitflags.h /usr/local/include/waitstatus.h
board.o: common.h vers.h legal.h board.h playerdb.h command.h variable.h
board.o: gamedb.h utils.h multicol.h
channel.o: stdinclude.h /usr/local/include/sys/types.h
channel.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
channel.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
channel.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
channel.o: /usr/local/include/strings.h /usr/local/include/string.h
channel.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
channel.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
channel.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
channel.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
channel.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
channel.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
channel.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
channel.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
channel.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
channel.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
channel.o: /usr/local/include/signal.h /usr/local/include/sigset.h
channel.o: /usr/local/include/math.h /usr/local/include/huge_val.h
channel.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
channel.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
channel.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
channel.o: /usr/local/include/sys/ttydefaults.h /usr/local/include/sys/wait.h
channel.o: /usr/local/include/waitflags.h /usr/local/include/waitstatus.h
channel.o: common.h vers.h legal.h channel.h network.h command.h variable.h
channel.o: rmalloc.h playerdb.h
command.o: stdinclude.h /usr/local/include/sys/types.h
command.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
command.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
command.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
command.o: /usr/local/include/strings.h /usr/local/include/string.h
command.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
command.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
command.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
command.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
command.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
command.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
command.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
command.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
command.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
command.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
command.o: /usr/local/include/signal.h /usr/local/include/sigset.h
command.o: /usr/local/include/math.h /usr/local/include/huge_val.h
command.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
command.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
command.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
command.o: /usr/local/include/sys/ttydefaults.h /usr/local/include/sys/wait.h
command.o: /usr/local/include/waitflags.h /usr/local/include/waitstatus.h
command.o: common.h vers.h legal.h rmalloc.h command.h variable.h
command.o: command_list.h comproc.h matchproc.h talkproc.h lists.h gameproc.h
command.o: adminproc.h playerdb.h ratings.h eco.h movecheck.h ficsmain.h
command.o: config.h utils.h multicol.h gamedb.h board.h network.h
talkproc.o: stdinclude.h /usr/local/include/sys/types.h
talkproc.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
talkproc.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
talkproc.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
talkproc.o: /usr/local/include/strings.h /usr/local/include/string.h
talkproc.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
talkproc.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
talkproc.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
talkproc.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
talkproc.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
talkproc.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
talkproc.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
talkproc.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
talkproc.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
talkproc.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
talkproc.o: /usr/local/include/signal.h /usr/local/include/sigset.h
talkproc.o: /usr/local/include/math.h /usr/local/include/huge_val.h
talkproc.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
talkproc.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
talkproc.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
talkproc.o: /usr/local/include/sys/ttydefaults.h
talkproc.o: /usr/local/include/sys/wait.h /usr/local/include/waitflags.h
talkproc.o: /usr/local/include/waitstatus.h common.h vers.h legal.h
talkproc.o: talkproc.h comproc.h command.h variable.h utils.h multicol.h
talkproc.o: ficsmain.h config.h playerdb.h network.h rmalloc.h channel.h
talkproc.o: gamedb.h board.h gameproc.h lists.h
talkproc.o: /usr/local/include/sys/resource.h
talkproc.o: /usr/local/include/resourcebits.h
comproc.o: stdinclude.h /usr/local/include/sys/types.h
comproc.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
comproc.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
comproc.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
comproc.o: /usr/local/include/strings.h /usr/local/include/string.h
comproc.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
comproc.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
comproc.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
comproc.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
comproc.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
comproc.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
comproc.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
comproc.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
comproc.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
comproc.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
comproc.o: /usr/local/include/signal.h /usr/local/include/sigset.h
comproc.o: /usr/local/include/math.h /usr/local/include/huge_val.h
comproc.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
comproc.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
comproc.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
comproc.o: /usr/local/include/sys/ttydefaults.h /usr/local/include/sys/wait.h
comproc.o: /usr/local/include/waitflags.h /usr/local/include/waitstatus.h
comproc.o: common.h vers.h legal.h talkproc.h comproc.h command.h variable.h
comproc.o: utils.h multicol.h ficsmain.h config.h playerdb.h network.h
comproc.o: rmalloc.h channel.h gamedb.h board.h gameproc.h ratings.h
comproc.o: formula.h lists.h eco.h /usr/local/include/sys/resource.h
comproc.o: /usr/local/include/resourcebits.h
matchproc.o: stdinclude.h /usr/local/include/sys/types.h
matchproc.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
matchproc.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
matchproc.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
matchproc.o: /usr/local/include/strings.h /usr/local/include/string.h
matchproc.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
matchproc.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
matchproc.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
matchproc.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
matchproc.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
matchproc.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
matchproc.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
matchproc.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
matchproc.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
matchproc.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
matchproc.o: /usr/local/include/signal.h /usr/local/include/sigset.h
matchproc.o: /usr/local/include/math.h /usr/local/include/huge_val.h
matchproc.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
matchproc.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
matchproc.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
matchproc.o: /usr/local/include/sys/ttydefaults.h
matchproc.o: /usr/local/include/sys/wait.h /usr/local/include/waitflags.h
matchproc.o: /usr/local/include/waitstatus.h common.h vers.h legal.h
matchproc.o: talkproc.h comproc.h command.h variable.h utils.h multicol.h
matchproc.o: ficsmain.h config.h playerdb.h network.h rmalloc.h channel.h
matchproc.o: gamedb.h board.h gameproc.h ratings.h formula.h lists.h eco.h
matchproc.o: /usr/local/include/sys/resource.h
matchproc.o: /usr/local/include/resourcebits.h
fics_addplayer.o: stdinclude.h /usr/local/include/sys/types.h
fics_addplayer.o: /usr/local/include/features.h
fics_addplayer.o: /usr/local/include/sys/cdefs.h /usr/local/include/stubs.h
fics_addplayer.o: /usr/local/include/gnu/types.h
fics_addplayer.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
fics_addplayer.o: /usr/local/include/strings.h /usr/local/include/string.h
fics_addplayer.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
fics_addplayer.o: /usr/local/include/dirstream.h
fics_addplayer.o: /usr/local/include/sys/stat.h /usr/local/include/statbuf.h
fics_addplayer.o: /usr/local/include/stdio.h stdarg.h
fics_addplayer.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
fics_addplayer.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
fics_addplayer.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
fics_addplayer.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
fics_addplayer.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
fics_addplayer.o: /usr/local/include/posix_opt.h
fics_addplayer.o: /usr/local/include/confname.h /usr/local/include/ctype.h
fics_addplayer.o: /usr/local/include/sys/errno.h /usr/local/include/signal.h
fics_addplayer.o: /usr/local/include/sigset.h /usr/local/include/math.h
fics_addplayer.o: /usr/local/include/huge_val.h /usr/local/include/__math.h
fics_addplayer.o: /usr/local/include/sys/time.h /usr/local/include/sys/file.h
fics_addplayer.o: /usr/local/include/sys/fcntl.h
fics_addplayer.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
fics_addplayer.o: /usr/local/include/sys/ttydefaults.h
fics_addplayer.o: /usr/local/include/sys/wait.h
fics_addplayer.o: /usr/local/include/waitflags.h
fics_addplayer.o: /usr/local/include/waitstatus.h common.h vers.h legal.h
fics_addplayer.o: utils.h multicol.h playerdb.h command.h variable.h
ficsmain.o: stdinclude.h /usr/local/include/sys/types.h
ficsmain.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
ficsmain.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
ficsmain.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
ficsmain.o: /usr/local/include/strings.h /usr/local/include/string.h
ficsmain.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
ficsmain.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
ficsmain.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
ficsmain.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
ficsmain.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
ficsmain.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
ficsmain.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
ficsmain.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
ficsmain.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
ficsmain.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
ficsmain.o: /usr/local/include/signal.h /usr/local/include/sigset.h
ficsmain.o: /usr/local/include/math.h /usr/local/include/huge_val.h
ficsmain.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
ficsmain.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
ficsmain.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
ficsmain.o: /usr/local/include/sys/ttydefaults.h
ficsmain.o: /usr/local/include/sys/wait.h /usr/local/include/waitflags.h
ficsmain.o: /usr/local/include/waitstatus.h common.h vers.h legal.h
ficsmain.o: ficsmain.h config.h network.h command.h variable.h channel.h
ficsmain.o: playerdb.h ratings.h utils.h multicol.h board.h talkproc.h
ficsmain.o: comproc.h eco.h
formula.o: /usr/local/include/ctype.h /usr/local/include/features.h
formula.o: /usr/local/include/sys/cdefs.h /usr/local/include/stubs.h config.h
formula.o: formula.h playerdb.h command.h variable.h gamedb.h
formula.o: /usr/local/include/sys/time.h board.h common.h vers.h legal.h
formula.o: stdinclude.h /usr/local/include/sys/types.h
formula.o: /usr/local/include/gnu/types.h /usr/local/include/stddef.h
formula.o: /usr/local/include/strings.h /usr/local/include/string.h
formula.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
formula.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
formula.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
formula.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
formula.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
formula.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
formula.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
formula.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
formula.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
formula.o: /usr/local/include/sys/errno.h /usr/local/include/signal.h
formula.o: /usr/local/include/sigset.h /usr/local/include/math.h
formula.o: /usr/local/include/huge_val.h /usr/local/include/__math.h
formula.o: /usr/local/include/sys/time.h /usr/local/include/sys/file.h
formula.o: /usr/local/include/sys/fcntl.h /usr/local/include/sys/ioctl.h
formula.o: /usr/local/include/ioctls.h /usr/local/include/sys/ttydefaults.h
formula.o: /usr/local/include/sys/wait.h /usr/local/include/waitflags.h
formula.o: /usr/local/include/waitstatus.h utils.h multicol.h rmalloc.h
formula.o: lists.h
gamedb.o: stdinclude.h /usr/local/include/sys/types.h
gamedb.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
gamedb.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
gamedb.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
gamedb.o: /usr/local/include/strings.h /usr/local/include/string.h
gamedb.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
gamedb.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
gamedb.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
gamedb.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
gamedb.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
gamedb.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
gamedb.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
gamedb.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
gamedb.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
gamedb.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
gamedb.o: /usr/local/include/signal.h /usr/local/include/sigset.h
gamedb.o: /usr/local/include/math.h /usr/local/include/huge_val.h
gamedb.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
gamedb.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
gamedb.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
gamedb.o: /usr/local/include/sys/ttydefaults.h /usr/local/include/sys/wait.h
gamedb.o: /usr/local/include/waitflags.h /usr/local/include/waitstatus.h
gamedb.o: common.h vers.h legal.h ficsmain.h config.h gamedb.h board.h
gamedb.o: playerdb.h command.h variable.h gameproc.h utils.h multicol.h
gamedb.o: rmalloc.h eco.h network.h
gameproc.o: stdinclude.h /usr/local/include/sys/types.h
gameproc.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
gameproc.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
gameproc.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
gameproc.o: /usr/local/include/strings.h /usr/local/include/string.h
gameproc.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
gameproc.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
gameproc.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
gameproc.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
gameproc.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
gameproc.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
gameproc.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
gameproc.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
gameproc.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
gameproc.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
gameproc.o: /usr/local/include/signal.h /usr/local/include/sigset.h
gameproc.o: /usr/local/include/math.h /usr/local/include/huge_val.h
gameproc.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
gameproc.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
gameproc.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
gameproc.o: /usr/local/include/sys/ttydefaults.h
gameproc.o: /usr/local/include/sys/wait.h /usr/local/include/waitflags.h
gameproc.o: /usr/local/include/waitstatus.h common.h vers.h legal.h command.h
gameproc.o: variable.h ficsmain.h config.h playerdb.h gamedb.h board.h
gameproc.o: gameproc.h movecheck.h utils.h multicol.h ratings.h rmalloc.h
gameproc.o: comproc.h matchproc.h formula.h eco.h network.h
lists.o: lists.h common.h vers.h legal.h multicol.h command.h variable.h
lists.o: utils.h /usr/local/include/stdio.h playerdb.h ratings.h rmalloc.h
lists.o: gamedb.h /usr/local/include/sys/time.h /usr/local/include/features.h
lists.o: /usr/local/include/sys/cdefs.h /usr/local/include/stubs.h board.h
lists.o: stdinclude.h /usr/local/include/sys/types.h
lists.o: /usr/local/include/gnu/types.h /usr/local/include/stddef.h
lists.o: /usr/local/include/strings.h /usr/local/include/string.h
lists.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
lists.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
lists.o: /usr/local/include/statbuf.h stdarg.h /usr/local/include/stdlib.h
lists.o: /usr/local/include/errno.h /usr/local/include/errnos.h
lists.o: /usr/local/include/sys/socket.h /usr/local/include/netinet/in.h
lists.o: /usr/local/include/endian.h /usr/local/include/bytesex.h
lists.o: /usr/local/include/arpa/inet.h /usr/local/include/netdb.h
lists.o: /usr/local/include/unistd.h /usr/local/include/posix_opt.h
lists.o: /usr/local/include/confname.h /usr/local/include/ctype.h
lists.o: /usr/local/include/sys/errno.h /usr/local/include/signal.h
lists.o: /usr/local/include/sigset.h /usr/local/include/math.h
lists.o: /usr/local/include/huge_val.h /usr/local/include/__math.h
lists.o: /usr/local/include/sys/time.h /usr/local/include/sys/file.h
lists.o: /usr/local/include/sys/fcntl.h /usr/local/include/sys/ioctl.h
lists.o: /usr/local/include/ioctls.h /usr/local/include/sys/ttydefaults.h
lists.o: /usr/local/include/sys/wait.h /usr/local/include/waitflags.h
lists.o: /usr/local/include/waitstatus.h comproc.h
makerank.o: /usr/local/include/stdio.h /usr/local/include/string.h
makerank.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
makerank.o: /usr/local/include/stubs.h /usr/local/include/stddef.h
makerank.o: /usr/local/include/ctype.h
movecheck.o: stdinclude.h /usr/local/include/sys/types.h
movecheck.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
movecheck.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
movecheck.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
movecheck.o: /usr/local/include/strings.h /usr/local/include/string.h
movecheck.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
movecheck.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
movecheck.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
movecheck.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
movecheck.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
movecheck.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
movecheck.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
movecheck.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
movecheck.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
movecheck.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
movecheck.o: /usr/local/include/signal.h /usr/local/include/sigset.h
movecheck.o: /usr/local/include/math.h /usr/local/include/huge_val.h
movecheck.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
movecheck.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
movecheck.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
movecheck.o: /usr/local/include/sys/ttydefaults.h
movecheck.o: /usr/local/include/sys/wait.h /usr/local/include/waitflags.h
movecheck.o: /usr/local/include/waitstatus.h common.h vers.h legal.h
movecheck.o: movecheck.h algcheck.h board.h gamedb.h utils.h multicol.h
movecheck.o: network.h command.h variable.h playerdb.h
multicol.o: stdinclude.h /usr/local/include/sys/types.h
multicol.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
multicol.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
multicol.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
multicol.o: /usr/local/include/strings.h /usr/local/include/string.h
multicol.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
multicol.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
multicol.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
multicol.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
multicol.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
multicol.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
multicol.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
multicol.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
multicol.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
multicol.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
multicol.o: /usr/local/include/signal.h /usr/local/include/sigset.h
multicol.o: /usr/local/include/math.h /usr/local/include/huge_val.h
multicol.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
multicol.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
multicol.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
multicol.o: /usr/local/include/sys/ttydefaults.h
multicol.o: /usr/local/include/sys/wait.h /usr/local/include/waitflags.h
multicol.o: /usr/local/include/waitstatus.h common.h vers.h legal.h
multicol.o: multicol.h utils.h rmalloc.h
network.o: stdinclude.h /usr/local/include/sys/types.h
network.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
network.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
network.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
network.o: /usr/local/include/strings.h /usr/local/include/string.h
network.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
network.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
network.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
network.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
network.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
network.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
network.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
network.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
network.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
network.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
network.o: /usr/local/include/signal.h /usr/local/include/sigset.h
network.o: /usr/local/include/math.h /usr/local/include/huge_val.h
network.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
network.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
network.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
network.o: /usr/local/include/sys/ttydefaults.h /usr/local/include/sys/wait.h
network.o: /usr/local/include/waitflags.h /usr/local/include/waitstatus.h
network.o: /usr/local/include/arpa/telnet.h common.h vers.h legal.h utils.h
network.o: multicol.h playerdb.h command.h variable.h network.h rmalloc.h
network.o: timeseal.h
playerdb.o: stdinclude.h /usr/local/include/sys/types.h
playerdb.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
playerdb.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
playerdb.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
playerdb.o: /usr/local/include/strings.h /usr/local/include/string.h
playerdb.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
playerdb.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
playerdb.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
playerdb.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
playerdb.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
playerdb.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
playerdb.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
playerdb.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
playerdb.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
playerdb.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
playerdb.o: /usr/local/include/signal.h /usr/local/include/sigset.h
playerdb.o: /usr/local/include/math.h /usr/local/include/huge_val.h
playerdb.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
playerdb.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
playerdb.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
playerdb.o: /usr/local/include/sys/ttydefaults.h
playerdb.o: /usr/local/include/sys/wait.h /usr/local/include/waitflags.h
playerdb.o: /usr/local/include/waitstatus.h common.h vers.h legal.h command.h
playerdb.o: variable.h comproc.h playerdb.h rmalloc.h utils.h multicol.h
playerdb.o: network.h ficsmain.h config.h channel.h gamedb.h board.h
playerdb.o: ratings.h
ratings.o: stdinclude.h /usr/local/include/sys/types.h
ratings.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
ratings.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
ratings.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
ratings.o: /usr/local/include/strings.h /usr/local/include/string.h
ratings.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
ratings.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
ratings.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
ratings.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
ratings.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
ratings.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
ratings.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
ratings.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
ratings.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
ratings.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
ratings.o: /usr/local/include/signal.h /usr/local/include/sigset.h
ratings.o: /usr/local/include/math.h /usr/local/include/huge_val.h
ratings.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
ratings.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
ratings.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
ratings.o: /usr/local/include/sys/ttydefaults.h /usr/local/include/sys/wait.h
ratings.o: /usr/local/include/waitflags.h /usr/local/include/waitstatus.h
ratings.o: common.h vers.h legal.h playerdb.h command.h variable.h ratings.h
ratings.o: gamedb.h board.h comproc.h lists.h ficsmain.h config.h utils.h
ratings.o: multicol.h
rmalloc.o: stdinclude.h /usr/local/include/sys/types.h
rmalloc.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
rmalloc.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
rmalloc.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
rmalloc.o: /usr/local/include/strings.h /usr/local/include/string.h
rmalloc.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
rmalloc.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
rmalloc.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
rmalloc.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
rmalloc.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
rmalloc.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
rmalloc.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
rmalloc.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
rmalloc.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
rmalloc.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
rmalloc.o: /usr/local/include/signal.h /usr/local/include/sigset.h
rmalloc.o: /usr/local/include/math.h /usr/local/include/huge_val.h
rmalloc.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
rmalloc.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
rmalloc.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
rmalloc.o: /usr/local/include/sys/ttydefaults.h /usr/local/include/sys/wait.h
rmalloc.o: /usr/local/include/waitflags.h /usr/local/include/waitstatus.h
rmalloc.o: common.h vers.h legal.h
utils.o: stdinclude.h /usr/local/include/sys/types.h
utils.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
utils.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
utils.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
utils.o: /usr/local/include/strings.h /usr/local/include/string.h
utils.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
utils.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
utils.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
utils.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
utils.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
utils.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
utils.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
utils.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
utils.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
utils.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
utils.o: /usr/local/include/signal.h /usr/local/include/sigset.h
utils.o: /usr/local/include/math.h /usr/local/include/huge_val.h
utils.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
utils.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
utils.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
utils.o: /usr/local/include/sys/ttydefaults.h /usr/local/include/sys/wait.h
utils.o: /usr/local/include/waitflags.h /usr/local/include/waitstatus.h
utils.o: common.h vers.h legal.h utils.h multicol.h playerdb.h command.h
utils.o: variable.h network.h rmalloc.h config.h
variable.o: stdinclude.h /usr/local/include/sys/types.h
variable.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
variable.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
variable.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
variable.o: /usr/local/include/strings.h /usr/local/include/string.h
variable.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
variable.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
variable.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
variable.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
variable.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
variable.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
variable.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
variable.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
variable.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
variable.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
variable.o: /usr/local/include/signal.h /usr/local/include/sigset.h
variable.o: /usr/local/include/math.h /usr/local/include/huge_val.h
variable.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
variable.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
variable.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
variable.o: /usr/local/include/sys/ttydefaults.h
variable.o: /usr/local/include/sys/wait.h /usr/local/include/waitflags.h
variable.o: /usr/local/include/waitstatus.h common.h vers.h legal.h
variable.o: variable.h playerdb.h command.h utils.h multicol.h ficsmain.h
variable.o: config.h rmalloc.h board.h
eco.o: stdinclude.h /usr/local/include/sys/types.h
eco.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
eco.o: /usr/local/include/stubs.h /usr/local/include/gnu/types.h
eco.o: /usr/local/include/sys/time.h /usr/local/include/stddef.h
eco.o: /usr/local/include/strings.h /usr/local/include/string.h
eco.o: /usr/local/include/sys/dir.h /usr/local/include/dirent.h
eco.o: /usr/local/include/dirstream.h /usr/local/include/sys/stat.h
eco.o: /usr/local/include/statbuf.h /usr/local/include/stdio.h stdarg.h
eco.o: /usr/local/include/stdlib.h /usr/local/include/errno.h
eco.o: /usr/local/include/errnos.h /usr/local/include/sys/socket.h
eco.o: /usr/local/include/netinet/in.h /usr/local/include/endian.h
eco.o: /usr/local/include/bytesex.h /usr/local/include/arpa/inet.h
eco.o: /usr/local/include/netdb.h /usr/local/include/unistd.h
eco.o: /usr/local/include/posix_opt.h /usr/local/include/confname.h
eco.o: /usr/local/include/ctype.h /usr/local/include/sys/errno.h
eco.o: /usr/local/include/signal.h /usr/local/include/sigset.h
eco.o: /usr/local/include/math.h /usr/local/include/huge_val.h
eco.o: /usr/local/include/__math.h /usr/local/include/sys/time.h
eco.o: /usr/local/include/sys/file.h /usr/local/include/sys/fcntl.h
eco.o: /usr/local/include/sys/ioctl.h /usr/local/include/ioctls.h
eco.o: /usr/local/include/sys/ttydefaults.h /usr/local/include/sys/wait.h
eco.o: /usr/local/include/waitflags.h /usr/local/include/waitstatus.h board.h
eco.o: gamedb.h command.h variable.h playerdb.h gameproc.h utils.h multicol.h
eco.o: common.h vers.h legal.h config.h
timeseal.o: /usr/local/include/stdio.h /usr/local/include/stdlib.h
timeseal.o: /usr/local/include/features.h /usr/local/include/sys/cdefs.h
timeseal.o: /usr/local/include/stubs.h /usr/local/include/stddef.h
timeseal.o: /usr/local/include/errno.h /usr/local/include/errnos.h
timeseal.o: /usr/local/include/strings.h /usr/local/include/string.h
timeseal.o: playerdb.h command.h variable.h network.h board.h gamedb.h
timeseal.o: /usr/local/include/sys/time.h
